config/routes.rb
Rails.application.routes.draw do
  root  "static_pages#home"
  get    "/help",    to:  "static_pages#help"
  get    "/about",   to:  "static_pages#about"
  get    "/contact", to:  "static_pages#contact"
  get    "/signup",  to:  "users#new"
  post   "/signup",  to:  "users#create"
  get    "/login",   to:  "sessions#new"
  post   '/login',   to:  "sessions#create"
  delete '/logout',  to:  "sessions#destroy"
  resources :users
  resources :microposts do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :micropost
  belongs_to :user
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size

  private

    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :comments
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def feed
    Micropost.where("user_id = ?", id)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    include SessionsHelper
    private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post

  def create
      @comment = @micropost.comments.create(comment_params)
      @comment.user_id = current_user.id
      @comment.save

      if @comment.save
        redirect_to root_url
      else
        render "static_pages/home"
      end
  end

  private

    def find_post
      @micropost = Micropost.find(params[:micropost_id])
    end

    def comment_params
        params.require(:comment).permit(:content, :user_id, :micropost_id)
   end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def show
    @micropost = Micropost.find params[:id]
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end

    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
     user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
    else
      flash[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end

   def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to My Blog"
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Update"
      redirect_to @user
    else
      render "edit"
    end

  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
        redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in user
    session[:user_id] = user.id
  end

   def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user? user
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "avatar")
  end
end

app/views/comments/_form.html.erb
<%= form_for ([micropost, micropost.comments.build]) do |f| %>

    <%= f.text_area :content %>
    <%= f.submit %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <!-- Footer -->
    <footer >
      <div class="container">
        <p class="m-0 text-center text-dark">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>
</footer>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
   <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <%= link_to "Home", root_path, class: "nav-link" %>
    </li>

    <% if logged_in? %>
      <li><%= link_to "Users", users_path, class: "nav-link" %></li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Profile", current_user, class: "dropdown-item" %>
          <%= link_to "Setting", edit_user_path(current_user), class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    <% else %>
        <li><%= link_to "Log in", login_path, class: "nav-link" %></li>
    <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render "layouts/shim" %>
  </head>
  <body>
  <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
  <%= render "layouts/footer" %>

    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
<div class="container bootstrap snippet">
  <div class="col-sm-12">
    <div class="panel panel-white post panel-shadow">
      <div class="post-heading">
        <div class="pull-left image">
          <%= gravatar_for micropost.user %>
        </div>
        <div class="pull-left meta">
          <div class="title h5">
            <a href="#"><b><%= micropost.user.name %></b></a>
            made a post.
          </div>
          <h6 class="text-muted time"><%= time_ago_in_words(micropost.created_at) + " ago"  %></h6>
        </div>
      </div>


      <div class="post-description">
        <p>
          <%= micropost.content %>
        </p>

        <div class="stats">
          <a href="#" class="btn btn-default stat-item">
            <i class="fa fa-thumbs-up icon"></i>2
          </a>
          <a href="#" class="btn btn-default stat-item">
            <i class="fa fa-share icon"></i>12
          </a>
          <% if current_user?(micropost.user) %>
          <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
          <% end %>
        </div>
      </div>

      <div class="post-footer">
        <%= form_for ([micropost, Comment.new]) do |f| %>
          <div class="input-group">
            <%= f.text_field :content, class: "form-control", placeholder: "Add a comment" %>
            <span class="input-group-addon">
              <a href="#"><i class="fa fa-edit"></i></a>
            </span>
          </div>
        <% end %>

          <ul class="comments-list">
            <% micropost.comments.each do |comment| %>
              <li class="comment">
                <a class="pull-left" href="#">
                  <%= gravatar_for comment.user %>
                </a>
                <div class="comment-body">
                  <div class="comment-heading">
                  <h4 class="user"><%= comment.user.name %></h4>
                  <h5 class="time"><%= time_ago_in_words(comment.created_at) + " ago" %></h5>
                  </div>
                  <p><%= comment.content %></p>
                </div>
              </li>
            <% end %>
          </ul>
      </div>
    </div>
  </div>
</div>

app/views/microposts/show.html.erb
<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
<div class="container bootstrap snippet">
  <div class="col-sm-12">
    <div class="panel panel-white post panel-shadow">
      <div class="post-heading">
        <div class="pull-left image">
          <%= gravatar_for @micropost.user %>
        </div>
        <div class="pull-left meta">
          <div class="title h5">
            <a href="#"><b><%= @micropost.user.name %></b></a>
            made a post.
          </div>
          <h6 class="text-muted time"><%= time_ago_in_words(@micropost.created_at) + " ago"  %></h6>
        </div>
      </div>

      <div class="post-description">
        <p>
          <%= @micropost.content %>
        </p>

        <div class="stats">
          <a href="#" class="btn btn-default stat-item">
            <i class="fa fa-thumbs-up icon"></i>2
          </a>
          <a href="#" class="btn btn-default stat-item">
            <i class="fa fa-share icon"></i>12
          </a>
        </div>
      </div>

      <div class="post-footer">
        <%= form_for ([@micropost, Comment.new]) do |f| %>
          <div class="input-group">
            <%= f.text_field :content, class: "form-control", placeholder: "Add a comment" %>
            <span class="input-group-addon">
              <a href="#"><i class="fa fa-edit"></i></a>
            </span>
          </div>
        <% end %>

          <ul class="comments-list">
            <% @micropost.comments.each do |comment| %>
              <li class="comment">
                <a class="pull-left" href="#">
                  <%= gravatar_for comment.user %>
                </a>
                <div class="comment-body">
                  <div class="comment-heading">
                  <h4 class="user"><%= comment.user.name %></h4>
                  <h5 class="time"><%= time_ago_in_words(comment.created_at) + " ago" %></h5>
                  </div>
                  <p><%= comment.content %></p>
                </div>
              </li>
            <% end %>
          </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <section class="micropost_form">
        <%= render "shared/micropost_form" %>
      </section>
    </aside>
      <div class="col-md-8">
        <h3>Micropost Feed</h3>
          <%= render 'shared/feed' %>
      </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="form-body">
    <div class="sa-innate-form">
        <%= form_for @user do |f| %>
        <%= render 'shared/error_messages', object: @user %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <%= f.label :password %>
        <%= f.password_field :password %>
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>
        <%= f.submit yield(:button_text), class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>
<% provide(:button_text, "Save changes") %>

<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= render "form" %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
   <li>
     <%= gravatar_for user, size: 50 %>
     <%= link_to user.name, user %>
     <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                              data: { confirm: "Sure?"} %>
       <% end %>
   </li>
   <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<% provide(:button_text, "Join Now") %>

<h1>Sign up</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>